### ISSUE TITLE
Assessment Tools log zit vol met NPE's

### ISSUE THREAD

**Issue by allardnaber** [rijksuniversiteit-groningen/b2-AssessmentTools#93]
AssessmentTools log files op staging zitten vol met nullpointerexceptions, op staging al 61MB voor de ene appserver. Op productie zelfde probleem.

`2019-12-06 00:00:04,553 ERROR  [n.r.b.a.h.AccessCheckHandler] - Error performing access check nl.rug.blackboard.assessment.handlers.SupportOwnExamAccessCheck
java.lang.NullPointerException: null
	at nl.rug.blackboard.assessment.handlers.AccessCheckUtil.isNestorSupport(AccessCheckUtil.java:17)
	at nl.rug.blackboard.assessment.handlers.SupportOwnExamAccessCheck.check(SupportOwnExamAccessCheck.java:23)
	at nl.rug.blackboard.assessment.handlers.AccessCheckHandler.lambda$checkRequest$0(AccessCheckHandler.java:43)
	at nl.rug.blackboard.assessment.handlers.RunOnceOnRequest.runOnce(RunOnceOnRequest.java:13)
	at nl.rug.blackboard.assessment.handlers.AccessCheckHandler.checkRequest(AccessCheckHandler.java:33)
	at nl.rug.blackboard.assessment.handlers.AbstractContextHandler.resolveKeys(AbstractContextHandler.java:23)`

**Comment by PeterFokkinga** [comment]
fixed in commit 878567972 / release 3400.191210.2
