### ISSUE TITLE
Assessment Tools configscherm niet toegankelijk voor System Admin

### ISSUE THREAD

**Issue by PeterFokkinga** [rijksuniversiteit-groningen/b2-AssessmentTools#94]
```
2019-12-10 21:51:48,555 DEBUG  [n.r.b.a.a.ConfigAction] - peter (94.214.196.122 GET [S] )
2019-12-10 21:51:49,078 ERROR  [b.p.s.SecurityUtil  ] - plug-in version: 3400.191210.1
2019-12-10 21:51:49,078 ERROR  [b.p.s.SecurityUtil  ] - blackboard version: 3400.0.4-rel.68+a1c490e
2019-12-10 21:51:49,078 ERROR  [b.p.s.SecurityUtil  ] - java version: 1.8.0_161 (Linux 2.6.32-754.18.2.el6.x86_64)
2019-12-10 21:51:49,078 ERROR  [b.p.s.SecurityUtil  ] - peter @ null from 94.214.196.122
2019-12-10 21:51:49,078 ERROR  [b.p.s.SecurityUtil  ] - browser: CHROME 78.0.3904 / MACOSX
2019-12-10 21:51:49,079 ERROR  [b.p.s.SecurityUtil  ] - referrer: https://nestor.rug.nl/webapps/RuG-AssessmentTools-bb_bb60/do/adminMain
2019-12-10 21:51:49,079 ERROR  [b.p.s.SecurityUtil  ] - GET /webapps/RuG-AssessmentTools-bb_bb60/do/config -> -1 bytes

2019-12-10 21:51:49,084 ERROR  [b.p.s.SecurityUtil  ] - stacktrace follows
blackboard.platform.security.AccessException: <b>Access Denied</b><br>Access to this resource is prohibited. (admin.AssessmentTools.config.EXECUTE)
	at blackboard.platform.security.SecurityUtil.checkEntitlement(SecurityUtil.java:220)
	at blackboard.platform.security.impl.EntitlementDelegate.checkEntitlement(EntitlementDelegate.java:44)
	at nl.rug.blackboard.assessment.data.AssessmentToolsEntitlement.checkEntitlement(AssessmentToolsEntitlement.java:34)
	at nl.rug.blackboard.assessment.actions.ConfigAction.checkEntitlement(ConfigAction.java:72)
	at nl.rug.blackboard.assessment.actions.ConfigAction.getForm(ConfigAction.java:34)
	
```

**Comment by PeterFokkinga** [comment]
misschien dat de restart na updaten van de building block helpt?

**Comment by PeterFokkinga** [comment]
Issue idd verholpen na herstart
